version: "3.0"
services:
    profile:
        build: ./profile-service
        tty: true
        ports:
            - "8000:9000"
        depends_on: 
            - auth
    auth:
        build: ./auth-service
        tty: true
        ports:
            - "9000:9000"
        depends_on: 
            - db
    db:
        image: mongo
        ports:
            - "27017:27017"